language: java

jdk:
  - oraclejdk8
addons:
  ssh_known_hosts: itcraft.su

script:
  - sudo apt-get install sshpass
  - sshpass -p $SECURE scp -r $TRAVIS_BUILD_DIR/standalone $SERVER_URL:/home/sa/deploy
  - sshpass -p $SECURE ssh -o StrictHostKeyChecking=no sa@$SERVER_ADDR screen -S infobot -X quit
  - sshpass -p $SECURE ssh sa@$SERVER_ADDR screen -dmS infobot bash -c 'cd /home/sa/runningbot/; java -jar /home/sa/runningbot/infobot.jar'


#deploy:
#  provider: script
#  script: mvn deploy