language: java

jdk:
  - oraclejdk8
addons:
  ssh_known_hosts: itcraft.su

before_deploy:
  - ssh $SERVER_URL "screen -S infobot -X quit"

deploy:
  provider: script
  script: mvn package
    - mvn org.codehaus.mojo:wagon-maven-plugin:1.0:upload -Dwagon.url=scp://$SERVER_URL -Dwagon.fromDir=standalone -Dwagon.includes=*.jar -Dwagon.toDir=/home/sa/deploy

after_deploy:
  - ssh $SERVER_URL "screen -dmS infobot bash -c 'cd /home/sa/runningbot/; java -jar /home/sa/runningbot/infobot.jar'"