language: java

jdk:
  - oraclejdk8
addons:
  ssh_known_hosts: itcraft.su

script:
  - sudo apt-get install sshpass
  - sshpass -p $SECURE ssh -o StrictHostKeyChecking=no sa@itcraft.su touch ./test


deploy:
  provider: script
  script: mvn deploy